[package]
name = "reth-primitives"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/paradigmxyz/reth"
readme = "README.md"
description = "Commonly used types in reth."

[dependencies]
# reth
reth-rlp = { path = "../common/rlp", features = [
    "std",
    "derive",
    "ethereum-types",
] }
reth-codecs = { version = "0.1.0", path = "../storage/codecs" }

# ethereum
ethers-core = { git = "https://github.com/gakonst/ethers-rs", default-features = false }
parity-scale-codec = { version = "3.2.1", features = ["derive", "bytes"] }
tiny-keccak = { version = "2.0", features = ["keccak"] }
ethbloom = { version = "0.13", features = ["codec"] }

# crypto
secp256k1 = { version = "0.24.2", default-features = false, features = [
    "alloc",
    "recovery",
] }

#used for forkid
crc = "1"
maplit = "1"

# misc
bytes = "1.2"
serde = "1.0"
thiserror = "1"
sucds = "0.5.0"
arbitrary = { version = "1.1.7", features = ["derive"], optional = true }
hex = "0.4"
hex-literal = "0.3"
modular-bitfield = "0.11.2"
derive_more = "0.99"

# proof related
triehash = "0.8"
# See to replace hashers to simplify libraries
plain_hasher = "0.2"
hash-db = "0.15"

[dev-dependencies]
arbitrary = { version = "1.1.7", features = ["derive"] }
serde_json = "1.0"
hex-literal = "0.3"
test-fuzz = "3.0.4"

# necessary so we don't hit a "undeclared 'std'": 
# https://github.com/paradigmxyz/reth/pull/177#discussion_r1021172198 
secp256k1 = "0.24.2"